#!/usr/bin/gawk -f

function usage() {
  print "ci-log: Fetch CI log from Jenkins using curl."
  print "USAGE: ci-log CI_BUILD_URL"
}

BEGIN {
  if (ARGC != 1) {
    job_url = ARGV[1]
    delete ARGV[1]
    ARGC--
  } else {
    usage()
  }
  # https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_debug/1641/
  if (match(job_url, /(https?):\/\/([^\/]+)\/(view\/.*\/)?job\/(.*)\/([0-9]+)\/?/, url)) {
    system("curl --compressed " url[1] "://" url[2] "/job/" url[4] "/" url[5] "/consoleText" " > " url[4] "-" url[5] ".txt")
  } else {
    print "Unable to extract consoleText url from " job_url > "/dev/stderr"
  }
}
